# Numpy_Libraries

In [6]:
import numpy as np

#numpy array
a=np.array([1,2,3,4,5,6,7,8])     # .array() will help to create the NumPy Array
a
print(type(a))

<class 'numpy.ndarray'>


In [7]:
a[0]    #indexing

1

In [8]:
a.shape   #Find the shape of the array

(8,)

In [7]:
b=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [10]:
print(b[0,3])
print(b[1,3])
print(b[0,4])
print(b[1,1])

4
9
5
7


In [11]:
b.shape

(2, 5)

In [8]:
#array slicing

print(b[0,1:4])

[2 3 4]


In [9]:
print(b[1,2:4])

[8 9]


In [14]:
#data type

c=np.array([[1,2,3,4,5.9],[6,7,8.7,9,10]],dtype='int')
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [15]:
c=np.array([[1,2,3,4,5.9],[6,7,8.7,9,10]],dtype='float')
c

array([[ 1. ,  2. ,  3. ,  4. ,  5.9],
       [ 6. ,  7. ,  8.7,  9. , 10. ]])

In [16]:
newarr=a.astype("i")
#newarr=a.astype("int")
#newarr=a.astype("float")
#newarr=a.astype("bool")
print(newarr)

[1 2 3 4 5 6 7 8]


In [17]:
#1D-2D reshape

arr=np.array([1,2,3,4,5,6,7,8,9])       
x=arr.reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
#multi-1D

y=b.reshape(-1)            # .reshape(-1) will help to display 2-D into the 1-D
print(y)

[ 1  2  3  4  5  6  7  8  9 10]


In [19]:
#iteratting array
                 #Sequence:- Collection of Datatype/values

for i in arr:    # i-->Iterating Variable   arr-->Sequence Variable        
    print(i)

1
2
3
4
5
6
7
8
9


In [20]:
#join array

a=np.array([10,20,30,40])
b=np.array([50,60,70,80])

c=np.concatenate((a,b),axis=0)   #adding two 1-D arr in Row wise 
#c=np.stack((a,b),axis=1)         #adding two 1-D arr in Column wise

print(c)


[10 20 30 40 50 60 70 80]


In [21]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

#c=np.concatenate((a,b),axis=0)   #adding two 2-D arr in Row wise 
#c=np.concatenate((a,b),axis=1)   #adding two 1-D arr in Column wise

#c=np.vstack((a,b))        #Vertital Stack(Row-Wise)-->along axis 0
#c=np.hstack((a,b))         #Horizontal Stack(Column-Wise)-->along axis 1
c=np.dstack((a,b))        #Depth Stack(Depth-Wise)---> 3D Structure-->along axis 2

print(c)


[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [22]:
#sort array

a=np.array([50,40,60,10]) 
print(np.sort(a))           # .sort() function will make the ascending order

[10 40 50 60]


In [23]:
print(np.zeros((4,4),dtype='int'))        #(4,4)--->(rows,column)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [24]:
print(np.zeros((5,3),dtype='int'))

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [25]:
print(np.ones((4,2),dtype='int'))

[[1 1]
 [1 1]
 [1 1]
 [1 1]]


In [26]:
print(np.full((3,3),3))          #((3,3),3)-->((rows ,columns),print the no. 3)          

[[3 3 3]
 [3 3 3]
 [3 3 3]]


In [27]:
print(np.arange(10))               #np.arange(stop)

[0 1 2 3 4 5 6 7 8 9]


In [28]:
print(np.arange(2,10))            #np.arange(start,stop)

[2 3 4 5 6 7 8 9]


In [29]:
print(np.arange(2,10,3))          #np.arange(start,stop,step)

[2 5 8]


In [30]:
#mathematical multiplication

a=np.array([1,2,3,4])
b=np.array([5,7,9,6])
print(np.add(a,b))


[ 6  9 12 10]


In [31]:
print(np.subtract(a,b))

[-4 -5 -6 -2]


In [32]:
print(np.multiply(a,b))

[ 5 14 27 24]


In [33]:
print(np.divide(a,b))

[0.2        0.28571429 0.33333333 0.66666667]


In [34]:
arr1=np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(np.sum(arr1,axis=1))    #Column(Horizontally) wise Sum up
print(np.sum(arr1,axis=0))    #Row(Vertically) wise Sum up
print(np.mean(arr1,axis=0))  
                  #Average(mean) of each column-->axis=0
print(np.mean(arr1,axis=1))  
                  #Average(mean) of each row-->axis=1


[15 40]
[ 7  9 11 13 15]
[3.5 4.5 5.5 6.5 7.5]
[3. 8.]


In [35]:
d=np.random.random((2,4))        #Give the Random Value   (2,4)--->(row,column)
print(d)

[[0.79349968 0.29113273 0.25573358 0.6124231 ]
 [0.15444206 0.5527579  0.38046258 0.38518997]]


In [36]:
#random integer values array within a specific range

c=np.random.randint(10,100,(4,5))    # (10,100,(3,5))--->(Take the random integer value between 10-100,(row,column))           
print(c)

[[50 48 62 52 52]
 [22 29 71 26 77]
 [41 52 52 28 91]
 [73 82 35 75 15]]


In [37]:
#array dimension
print(c.shape)

(4, 5)


In [38]:
print(c.ndim)

2


In [39]:
#number of elements in array

print(c.size)

20


In [40]:
#Checking the datatype of the values in an array

print(c.dtype)

int32


In [41]:
#Array of evenly spaced values--->Specifying the no. of values required

d=np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [42]:
#Convert the List to a numpy array

list=[10,20,20,20,50]
np_array=np.asarray(list)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

In [43]:
c=np.random.randint(10,90,(5,5))
print(c)

[[80 46 46 87 59]
 [54 85 81 78 81]
 [40 76 49 49 13]
 [21 11 70 18 86]
 [74 75 35 11 48]]
